#!/bin/bash

FOLDER=samples

error() {
  echo -e "\e[31m$1\e[0m"
  exit
}

# Check whether enough arguments were passed.
if [ $# -ne 1 ] ; then
  error "Usage: ./create-user USER_NAME@DOMAIN_NAME"
fi

# Check whether the user already exists.
if [ -d $FOLDER/$1 ] ; then
  error "User $FOLDER/$1 already exists"
fi

# Generate the folders in samples.
mkdir $FOLDER/$1
touch $FOLDER/$1/blacklist.txt
touch $FOLDER/$1/whitelist.txt
touch $FOLDER/$1/requests.json
mkdir $FOLDER/$1/mails
touch $FOLDER/$1/mails/.gitkeep
mkdir $FOLDER/$1/mails/requested
touch $FOLDER/$1/mails/requested/.gitkeep
mkdir $FOLDER/$1/mails/sent
touch $FOLDER/$1/mails/sent/.gitkeep


# TODO : generate asymetric keys and certificates.
